version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      # checkout the repository
      - checkout

      - run:
          name: build site static pages
          command: |
            cd ~/hugo
            hugo

      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy
      - deploy:
          name: deploy to wweir.cc
          command: |
            ssh-keyscan wweir.cc >> ~/.ssh/known_hosts
            cd ~/hugo/public/
            rsync -avz -e ssh . root@wweir.cc:/var/www/html
